import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from '@/components/Navigation';
import DotGrid from "@/components/DotGrid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
        suppressHydrationWarning
      >
        {/* <DotGrid
          className="absolute inset-0 pointer-events-none"
          style={{ zIndex: -1 }}
          maxSpeed={0.5}
          speedTrigger={100}
          proximity={160}
          resistance={200}
          returnDuration={0.5}
          shockRadius={250}
          shockStrength={5}/> */}
        <main className="">
          {children}
        </main>
        <Navigation />
      </body>
    </html>
  );
}
